########## Spring AUTO CONFIG ###############
spring:
  resources:
    chain:
      cache: false
      strategy:
        content:
          enabled: true
          paths: /**
  http:
    multipart:
      enabled: true
      max-file-size: 100Mb
      max-request-size: 1000Mb
  profiles:
    active: default
  druid:
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

######### MYBATIS AUTO CONFIG ###############
mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: com.wtc.admin.performance.model
